//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public article()
        {
            this.comment = new HashSet<comment>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string thumbnail { get; set; }
        public string contents { get; set; }
        public Nullable<short> categoryId { get; set; }
        public Nullable<bool> status { get; set; }
        public string seoLink { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> articleView { get; set; }
    
        public virtual category category { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comment { get; set; }
    }
}
