//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public Nullable<int> articleId { get; set; }
        public string name { get; set; }
        public string eMail { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string message { get; set; }
        public string webSite { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual article article { get; set; }
    }
}
