//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class projes
    {
        public int id { get; set; }
        public string projeName { get; set; }
        public string thumbnail { get; set; }
        public string contents { get; set; }
        public string language { get; set; }
        public string linkedinLink { get; set; }
        public string githunLink { get; set; }
        public string seoLink { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string productLink { get; set; }
    }
}
