//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class siteSettings
    {
        public short id { get; set; }
        public string facebook { get; set; }
        public string googleplus { get; set; }
        public string twitter { get; set; }
        public string linkedin { get; set; }
        public string siteName { get; set; }
        public string mail { get; set; }
        public string googlemapsLink { get; set; }
        public string seoTitle { get; set; }
        public string seoDescription { get; set; }
        public string seoAuthor { get; set; }
        public string seoAbstract { get; set; }
        public string seoCopyright { get; set; }
        public string seoDesigner { get; set; }
        public string seoKeywords { get; set; }
    }
}
